apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: third-party
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:MichaelRobotics/velero-demo.git
    targetRevision: HEAD
    path: third-party
  destination:
    server: https://kubernetes.default.svc
    namespace: a-team
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
