apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: third-party
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vfarcic/velero-demo
    targetRevision: HEAD
    path: third-party
  destination:
    server: https://kubernetes.default.svc
    namespace: a-team
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
