---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlas-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: atlas-operator
    repoURL: ghcr.io/ariga/charts
    targetRevision: 0.6.1
  destination:
    server: https://kubernetes.default.svc
    namespace: atlas-operator
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
