apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: silly-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vfarcic/velero-demo
    targetRevision: HEAD
    path: yaml/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
