apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - persistent-volume.yaml
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: silly-demo
    spec:
      template:
        spec:
          containers:
          - name: silly-demo
            env:
            - name: DB
              value: fs
            volumeMounts:
              - mountPath: "/cache"
                name: silly-demo-cache
          volumes:
            - name: silly-demo-cache
              persistentVolumeClaim:
                claimName: silly-demo-cache