apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silly-demo-cache
  labels:
    app.kubernetes.io/name: silly-demo
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
